// https://www.universia.net/cl/actualidad/orientacion-academica/frases-motivadoras-estudiantes-busca-motivacion-1137358.html
// https://www.businessinsider.es/50-mejores-frases-motivacionales-estudiantes-857297
var all_phrases = [
    ["A través de otros nos convertimos en nosotros mismos.", "Lev S. Vygotsky"],
    ["Acepta la responsabilidad en tu vida. Sé consciente de que serás tú quien te llevará a donde quieres ir, nadie más.", "Les Brown"],
    ["Adquirir desde jóvenes tales o cuáles hábitos no tiene poca importancia: tiene una importancia absoluta.", "Aristóteles"],
    ["Aprender es como remar contra corriente: en cuanto se deja, se retrocede.", "Edward Benjamin Britten"],
    ["Aprender sin reflexionar es una ocupación inútil.", "Confucio"],
    ["Cada logro comienza con la decisión de intentarlo.", "Gail Devers"],
    ["Con mis maestros he aprendido mucho; con mis colegas, más; con mis alumnos todavía más.", "Proverbio hindú"],
    ["El acto de desobediencia, como acto de libertad, es el comienzo de la razón.", "Erich Fromm"],
    ["El aprendizaje es un simple apéndice de nosotros mismos; dondequiera que estemos, está también nuestro aprendizaje.", "William Shakespeare"],
    ["El aprendizaje no es un deporte para espectadores.", "D. Blocher"],
    ["El auténtico problema no es si las máquinas piensan, sino si lo hacen los hombres.", "B.F. Skinner"],
    ["El colmo de la estupidez es aprender lo que luego hay que olvidar.", "Erasmo de Rotterdam"],
    ["El éxito consiste en ir de fracaso en fracaso sin pérdida de entusiasmo.", "Winston Churchill"],
    ["El éxito requiere de persistencia, la habilidad de no rendirse en la cara del fracaso. Creo que el estilo optimista es la llave a la persistencia.", "Martin Seligman"],
    ["El verdadero discípulo es el que supera al maestro.", "Aristóteles"],
    ["El viaje es la recompensa.", "Proverbio chino"],
    ["Encuentro la televisión muy educativa. Cada vez que alguien la enciende, me retiro a otra habitación y leo un libro.", "Groucho Marx"],
    ["Es más sabio averiguar que suponer.", "Mark Twain"],
    ["Fuera del perro, un libro es probablemente el mejor amigo del hombre, y dentro del perro probablemente está demasiado oscuro para leer.", "Groucho Marx"],
    ["Hay la misma diferencia entre un sabio y un ignorante que entre un hombre vivo y un cadáver.", "Aristóteles"],
    ["Haz una cosa al día que te dé miedo.", "Eleanor Roosevel"],
    ["Hoy un lector, mañana un líder.", "Margaret Fuller"],
    ["La causa primaria de la infelicidad nunca es la situación, sino tus pensamientos sobre ella. Sé consciente de los pensamientos que estás teniendo.", "Eckhart Tolle"],
    ["La creatividad es la inteligencia pasándolo bien.", "Albert Einstein"],
    ["La cultura se adquiere leyendo libros; pero el conocimiento del mundo, que es mucho más necesario, sólo se alcanza leyendo a los hombres y estudiando las diversas ediciones que de ellos existen.", "Lord Chesterfield"],
    ["La gente exitosa estudia para ganar conocimientos, no para ganar carreras.", "Udayveer Singh"],
    ["La gente exitosa y no exitosa no varían mucho en sus habilidades. Varían en sus deseos de alcanzar su potencial.", "John Maxwell"],
    ["La inteligencia consiste no solo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica.", "Aristóteles"],
    ["La mejor forma de predecir el futuro es crearlo.", "Abraham Lincoln"],
    ["La tarea que debemos establecer para nosotros mismos no es estar seguros, sino ser capaces de tolerar la inseguridad.", "Erich Fromm"],
    ["La verdad tiene estructura de ficción.", "Jacques Lacan"],
    ["Las oportunidades no ocurren, las creas tú.", "Chris Grosser"],
    ["Lo poco que he aprendido carece de valor, comparado con lo que ignoro y no desespero en aprender.", "René Descartes"],
    ["Lo que con mucho trabajo se adquiere, más se ama.", "Aristóteles"],
    ["Lo único que se interpone entre tú y tu sueño es la voluntad de intentarlo y la creencia de que es posible conseguirlo.", "Joel Brown"],
    ["Los desafíos hacen la vida interesante y superarlos la hace significativa.", "Joshua J. Marine"],
    ["Los sabios son los que buscan la sabiduría; los necios piensan ya haberla encontrado.", "Napoleón Bonaparte"],
    ["Me lo contaron y lo olvidé; lo vi y lo entendí; lo hice y lo aprendí.", "Confucio"],
    ["No es normal saber lo que queremos. Es un extraño y difícil logro psicológico.", "Abraham Maslow"],
    ["No fuisteis criados para vivir como bestias, sino para seguir en pos de la virtud y la sabiduría.", "Dante Alighieri"],
    ["No hay ascensor al éxito, tienes que tomar las escaleras.", "Autor desconocido"],
    ["No hay sustituto del trabajo duro.", "Thomas Edison"],
    ["No juzgues cada día por lo que cosechas, sino por las semillas que plantas.", "Robert Louis Stevenson"],
    ["No se trata de donde vienes, sino de donde vas.", "Ella Fitzgerald"],
    ["No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.", "Jack Canfield"],
    ["Nuestra mayor debilidad reside en rendirnos. La forma más segura de tener éxito es intentarlo una vez más.", "Thomas A. Edison"],
    ["Nunca consideres el estudio como una obligación, sino como una oportunidad para penetrar en el bello y maravilloso mundo del saber.", "Albert Einstein"],
    ["Odié cada minuto de entrenamiento, pero dije, no te rindas. Sufre ahora y vive el resto de tu vida como un campeón.", "Muhammad Ali"],
    ["Olvida las razones de por qué no funcionará y cree en la única razón por la que lo hará.", "Autor desconocido"],
    ["Recordar es el mejor modo de olvidar.", "Sigmund Freud"],
    ["Si no persigues lo que quieres, nunca lo tendrás. Si no vas hacia delante, siempre estarás en el mismo lugar.", "Nora Roberts"],
    ["Si quieres aprender, enseña.", "Cicerón"],
    ["Todo hombre que conozco es superior a mí en algún sentido. En ese sentido, aprendo de él.", "Ralph Waldo Emerson"],
    ["Todos nuestros sueños se pueden volver realidad si tenemos el coraje de perseguirlos.", "Walt Disney"],
    ["Tus aspiraciones son tus posibilidades.", "Samuel Johnson"],
    ["Vive como si fueses a morir mañana. Aprende como si fueses a vivir siempre.", "Mahatma Gandhi"],
    ["Yo no enseño a mis alumnos, solo les proporciono las condiciones en las que puedan aprender.", "Albert Einstein"]
]